import turtle
tur=turtle.Turtle()

def writeNumber(num):
    tur.penup()
    tur.forward(200)
    tur.write(num)
    tur.back(200)
    tur.pendown()
    
tur.seth(90)

writeNumber(12)
tur.left(30)
writeNumber(11)
tur.left(30)
writeNumber(10)
tur.left(30)
writeNumber(9)
tur.left(30)
writeNumber(8)
tur.left(30)
writeNumber(7)
tur.left(30)
writeNumber(6)
tur.left(30)
writeNumber(5)
tur.left(30)
writeNumber(4)
tur.left(30)
writeNumber(3)
tur.left(30)
writeNumber(2)
tur.left(30)
writeNumber(1)
tur.left(30)

turtle.done()
turtle.exitonclick()